[workspace]
members = [".", "js", "python"]
resolver = "2"

[workspace.package]
version = "0.1.10"
authors = ["Ivan Malison <ivanmalison@gmail.com>"]
license = "MIT"
repository = "https://github.com/rlrml/subtr-actor"
edition = "2021"

[package]
name = "subtr-actor"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
keywords = ["rocket-league"]
categories = ["parsing"]
description = "Rocket League replay transformer"

[dependencies]
anyhow = "1.0.98"
boxcars = "0.10.10"
derive-new = "0.7.0"
float-ord = "0.3.2"
glam = "0.30.4"
lazy_static = "1.5.0"
log = "0.4.27"
ndarray = "0.16.1"
paste = "1.0.15"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"

[badges.github]
repository = "rlrml/subtr-actor"

[badges.maintenance]
status = "actively-developed"

