[package]
authors = ["Ivan Malison <ivanmalison@gmail.com>"]
license = "MIT"
name = "subtr-actor"
version = "0.1.1"
edition = "2021"
repository = "https://github.com/rlrml/subtr-actor"
keywords = ["rocket-league"]
categories = ["parsing"]
description = "Rocket League replay transformer"

[dependencies]
anyhow = "1.0.71"
boxcars = "0.9.9"
derive-new = "0.5.9"
float-ord = "0.3.2"
glam = "0.23.0"
lazy_static = "1.4.0"
log = "0.4.17"
ndarray = "0.15.6"
paste = "1.0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.96"
thiserror = "1.0.40"

[badges.github]
repository = "rlrml/subtr-actor"

[badges.maintenance]
status = "actively-developed"

